config/routes.rb
Rails.application.routes.draw do
  
  namespace :admins_backoffice do
    get 'welcome/index'   #dashboard
    resources :admins #admins
    resources :subjects  #assuntos
    resources :questions  #Perguntas
  end
  namespace :site do
    get 'welcome/index'
    get 'search', to: 'search#questions'
    get 'subject/:subject_id/:subject', to: 'search#subject', as: 'search_subject'
    post 'answer', to: 'answer#question'
  end
  namespace :users_backoffice do
    get 'welcome/index'
    get 'profile', to: 'profile#edit'
    patch 'profile', to: 'profile#update'
  end

  devise_for :admins, skip: [:registrations]
  devise_for :users
  
  get 'inicio', to: 'site/welcome#index'
  root to: 'site/welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  #kaminari
  paginates_per 5
end

app/models/admin_statistic.rb
class AdminStatistic < ApplicationRecord
    EVENTS = {
        total_users: "TOTAL_USERS",
        total_questions: "TOTAL_QUESTIONS"
    }

    scope :total_users, -> {
        find_by_event(EVENTS[:total_users]).value
    }
    scope :total_questions, -> {
        find_by_event(EVENTS[:total_questions]).value
    }
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question

  #kaminari
  paginates_per 5
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :subject,counter_cache: true, inverse_of: :questions
  has_many :answers
  accepts_nested_attributes_for :answers, reject_if: :all_blank, allow_destroy: true

  #after_create :set_statistic

  #kaminari
  paginates_per 5

  #Scopes
  scope :_search_subject_, ->(page, subject_id){
    includes(:answers, :subject).where(subject_id: subject_id).page(page)
  }

  scope :_search_, ->(page, term){
    includes(:answers, :subject).where("description LIKE ?", "%#{term.downcase}%").page(page)
  }

  scope :last_questions, ->(page){
    includes(:answers, :subject).order('created_at desc').page(page)
  }

  private
    def set_statistic
      AdminStatistic.set_event(AdminStatistic::EVENTS[:total_users])
    end
end

app/models/subject.rb
class Subject < ApplicationRecord
    has_many :questions
#kaminari
paginates_per 10
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one :user_profile
  accepts_nested_attributes_for :user_profile, reject_if: :all_blank

  #after_create :set_statistic

  def full_name
    [self.first_name, self.last_name].join(' ')
  end

  private
    def set_statistic
      AdminStatistic.set_event(AdminStatistic::EVENTS[:total_questions])
    end
end

app/models/user_profile.rb
class UserProfile < ApplicationRecord
  belongs_to :user
  has_one_attached :avatar
end

app/models/user_statistic.rb
class UserStatistic < ApplicationRecord
  belongs_to :user

  #virtual attribute
  def total_questions
    self.right_questions + self.wrong_questions
  end

  def self.set_statistic(answer, current_user)
    if !!current_user
      user_statistic = UserStatistic.find_or_create_by(user: current_user)
      answer.correct? ? user_statistic.right_questions += 1 : 
      user_statistic.wrong_questions += 1
      user_statistic.save
    end
  end


end

app/controllers/admins_backoffice_controller.rb
class AdminsBackofficeController < ApplicationController
    before_action :authenticate_admin!
    layout 'admins_backoffice'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    # Set Layout
    layout :layout_by_resource





    protected
        def layout_by_resource
            if devise_controller? && resource_class == Admin
                "admin_devise"
            elsif devise_controller? && resource_class == User
                "user_devise"
            else
                "application"
            end
        end

end

app/controllers/site/answer_controller.rb
class Site::AnswerController < SiteController
    layout 'site'
    def question
       @answer = Answer.find(params[:answer_id])
       UserStatistic.set_statistic(@answer, current_user)
    end

end

app/controllers/site/search_controller.rb
class Site::SearchController < SiteController
    layout 'site'
    def questions
        @questions = Question._search_(params[:page], params[:term])
    end

    def subject
        @questions = Question._search_subject_(params[:page], params[:subject_id])
        
    end
end

app/controllers/site/welcome_controller.rb
class Site::WelcomeController < SiteController
  layout 'site'
  def index
    @questions = Question.last_questions(params[:page])
    @questions2 = Question.all
  end
end

app/controllers/site_controller.rb
class SiteController < ApplicationController
end

app/controllers/users_backoffice_controller.rb
class UsersBackofficeController < ApplicationController
    before_action :authenticate_user!
    before_action :build_profile
    layout 'users_backoffice'

    private
        def build_profile
        current_user.build_user_profile if current_user.user_profile.blank?
        end
end

app/helpers/admins_backoffice/admins_helper.rb
module AdminsBackoffice::AdminsHelper
end

app/helpers/admins_backoffice/subjects_helper.rb
module AdminsBackoffice::SubjectsHelper
end

app/helpers/admins_backoffice/welcome_helper.rb
module AdminsBackoffice::WelcomeHelper
end

app/helpers/admins_backoffice_helper.rb
module AdminsBackofficeHelper
    def translate_attribute(object = nil, method = nil)
        if object && method
            object.model.human_attribute_name(method)
        else
            "Informe os parametros corretos"
        end   
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/site/answer_helper.rb
module Site::AnswerHelper
end

app/helpers/site/search_helper.rb
module Site::SearchHelper
end

app/helpers/site/welcome_helper.rb
module Site::WelcomeHelper
end

app/helpers/site_helper.rb
module SiteHelper
    def mensagem_inicial
        case params[:action]
        when 'index'
            "Últimas perguntas cadastradas ..."
        when 'questions'
            "Resultados para o termo \"#{params[:term]}\"..."
        when 'subject'
            "Mostrando questões para o assunto \"#{params[:subject]}\"..."
        end
    end
end

app/helpers/users_backoffice/profile_helper.rb
module UsersBackoffice::ProfileHelper
    def gender_select(user, current_gender)
        user.user_profile.gender == current_gender ? 'btn-primary' : 'btn-default'        
    end
end

app/helpers/users_backoffice/welcome_helper.rb
module UsersBackoffice::WelcomeHelper
end

app/helpers/users_backoffice_helper.rb
module UsersBackofficeHelper
    def avatar_url
        avatar = current_user.user_profile.avatar
        avatar.attached? ? avatar : 'img.jpg'
    end
end

app/views/site/search/questions.html.erb
<%= render partial: 'site/shared/questions' %>

app/views/site/search/subject.html.erb
<%= render partial: 'site/shared/questions' %>

app/views/site/shared/_questions.html.erb
<div class="jumbotron">
    <h3><%= mensagem_inicial %></h3>
    
    
</div>





<% @questions.each do |question| %>
    <%= form_with url: site_answer_path do |form| %>
        <div class="panel panel-default">
            <div class="panel-heading">                
                <h3 class="panel-title">
                    <span class="label label-info" style="margin-right: 10px">
                        <%="#{question.subject.description}"%>
                    </span>  
                    <%= question.description %>               
                </h3>
                
            </div>
            <% if user_signed_in? %>
                <div class="panel-body">
                    <ul>
                        <% question.answers.each do |answer| %>                       
                            <li style="list-style:none;">
                                <div class="radio">
                                    <label>
                                        <%= radio_button_tag 'answer_id', answer.id %>
                                        <%=answer.description%>
                                    <label>
                                </div>
                            </li>
                        <% end %>
                        
                        <li style="list-style:none;">
                            <%= form.submit "Responder", class:"btn btn-default", id: "submit_#{question.id}" %>
                        </li>
                        
                    </ul>      
                </div>
            <% end %>
            
        </div>
    <% end %>
<% end %>
<div class="text-center">
    <%= paginate @questions %>
<div>